const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const out=path.resolve(__dirname,'../../assets/production/animated/v001');
const manifest=JSON.parse(fs.readFileSync(path.join(out,'manifest.json'),'utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
const cards=manifest.characters.map(c=>{
 const pose=`${c.id}/Wave-0.50.png`,locomotion=`${c.id}/${c.locomotion.clip}-0.50.png`;
 for(const file of [pose,locomotion,c.glb,c.blend])assert.ok(fs.existsSync(path.join(out,file)),file);
 const viewer=`../../viewer.html?model=animated/v001/${c.glb}&amp;name=${encodeURIComponent(c.label+' · animaciones')}`;
 return `<article><a class="image-link" href="${viewer}" aria-label="Revisar animaciones: ${esc(c.label)}"><img src="${pose}" width="560" height="672" loading="lazy" alt="${esc(c.label)} saludando, render del GLB animado"></a><div class="info"><h2>${esc(c.label)}</h2><p>${c.bones} huesos · 5 clips · ${(c.bytes/1e6).toFixed(2)} MB<br>${c.triangles.toLocaleString('es')} triángulos · ${c.material_primitives} primitivas de material</p><a class="primary" href="${viewer}">Revisar animaciones</a><div class="links"><a href="${c.glb}" download>GLB</a><a href="${c.blend}" download>Blender</a><a href="${c.id}/asset.json">Ficha</a><a href="${c.id}/verification.json">Pruebas</a><a href="${locomotion}">Postura de locomoción</a></div></div></article>`;
}).join('\n');
const html=`<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>YAIS · Rigs y animaciones</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#102b32;color:#edf5ed;font:17px/1.6 system-ui}main{max-width:1180px;padding:28px;margin:auto}a{color:#ffd277;display:inline-flex;align-items:center;min-height:44px;min-width:44px}a:focus-visible{outline:3px solid white;outline-offset:3px}h1{font-size:clamp(28px,5vw,46px);line-height:1.15}.tag{color:#b9ddd1}.notice{padding:18px;background:#204149;border-left:4px solid #ffd277;border-radius:10px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:20px;margin:30px 0}article{background:#204149;border-radius:18px;overflow:hidden}.image-link{display:block}img{width:100%;height:auto;display:block}.info{padding:20px}h2{font-size:1.3rem;margin-top:0}.info p{font-size:.9rem}.primary{background:#ffd277;color:#132b31;font-weight:700;padding:10px 16px;border-radius:12px}.links{display:flex;flex-wrap:wrap;gap:4px 16px;margin-top:12px}.links a{font-size:.9rem}code{overflow-wrap:anywhere}@media(max-width:500px){main{padding:16px}}
</style><main><a href="../../index.html">← Catálogo completo</a><p class="tag">LA ISLA DE LOS ACUERDOS · PRIMER RIG DE DEFORMACIÓN</p><h1>Los personajes ya se mueven.</h1><p>5 personajes · 25 clips exportados · originales estáticos conservados. Generación secuencial con Blender en segundo plano, CPU y dos hilos.</p><div class="notice"><strong>Cómo revisarlos:</strong> abre un personaje, elige un movimiento y pulsa «Reproducir». Puedes pausar, cambiar la velocidad y mover la línea de tiempo. No necesitas abrir Blender. Los renders de esta página son posturas de los GLB reales, no imágenes conceptuales.</div><div class="grid">${cards}</div><h2>Qué incluye esta etapa</h2><p>Reposo, caminar (rodar para la silla), saludo, escucha y gesto de conversación. Todos son movimientos en el sitio. La integración debe desplazar al personaje; aquí no hay navegación ni colisiones de juego.</p><h2>Qué falta</h2><p>Retopología y limpieza de articulaciones, dedos y expresiones faciales, correr, transiciones en el motor, LOD, compresión y pruebas de rendimiento en el dispositivo objetivo. No es todavía una entrega optimizada para móvil/aula: el conjunto pesa ${(manifest.total_glb_bytes/1e6).toFixed(2)} MB sin comprimir. El visor solo descarga un personaje a la vez.</p><p>Los renders se abren sin conexión. El visor interactivo necesita el servidor local y acceso al componente de Google CDN. <a href="manifest.json">Manifiesto técnico</a> · <a href="../../../../PRODUCCION-3D.md">Estado y reanudación</a></p></main></html>`;
fs.writeFileSync(path.join(out,'index.html'),html);console.log('Galería de 5 personajes animados generada.');
